### ISSUE TITLE
Beaches completely disappear when reducing continent scale

### ISSUE THREAD

**Issue by Jokkaj** [TerraForged/TerraForged#102]
**Description**
Hi, Since 1.13 update acquatic I wanted to create an all-islands tropical world so I lowered a lot the continent scale, but I noticed that when I lower the continent scale under 600-500 beaches disappear (there are some blocks of sand around the world but they are pretty rare and this gets worse when you lower the continent scale under 200).
I tried to lower the sealevel and increasing the erosion but that doesn't help.
It would be nice to have an addiotional "beaches size" slider.

**How to reproduce**
Just lower the continent scale and increase ocean size a lot to create a lot of islands

**Additional information**
here I have some photos

**Comment by dags-** [comment]
Hi. Certain settings can only be pushed so far before things will start falling apart. The engine has simply been designed to be used at a larger scale than you're aiming for, with the continent shapes being a fundemental building block for all the terrain and biomes that come after.

I provide access to the 'extreme' options to users because I think it's nice/fun to have that range of configurability but I can't provide any guarantee of quality/playability the further they choose to deviate from the default settings
