### ISSUE TITLE
Tree Generation Customization Suggestions

### ISSUE THREAD

**Issue by archizackture** [TerraForged/TerraForged#110]
**Is your feature request related to a problem? Please describe.**
Because much of the terrain that gets generated has height levels above y=120, we end up with massive bald, treeless areas of terrain, as well as grass color changes without any foliage changes to match. Additionally, some biomes, mainly the temperate and hot biomes, would look better with trees generating all the way, or most of the way, to maximum height.

IRL, I live in the Appalachian Mountains which are forested all the way from top to bottom. In the highest elevations, however, the trees are shorter and are mostly evergreens, though not necessarily more sparse. The Carpathians are another example of a mountain range that is forested at all elevations. Therefore I believe it makes sense to have the option for trees to generate at all elevations (or at least up to 220 or 240 or so) in certain biomes/temperatures.

**Describe the solution you'd like**
It would be great to have a flora customization menu (or possibly an addition to the temperature/moisture menu) where we can adjust how trees will generate in relation to both the height of the terrain and the temperature of the biome. Ideally, it would be great if I can use the sliders to have forested peaks in forest-dominant biomes (forest and taiga variants, jungle, savannah, etc), define elevations where tree generation prioritizes shorter trees and/or generation becomes more sparse, etc.

**Additional context**
I believe Dags mentioned on the Discord that tree options will be coming soon, so I figured I should suggest some ways that I believe such customization could work based on what I have seen in my test worlds and in reality.

**Comment by dags-** [comment]
I'll be working more on feature placements in the future, although this will need to be controlled via data (ie json files) so no fancy slider-y things. The treeline thing could have a slider though

**Comment by demonJ5** [comment]
Definitely agree with this sentiment. The less steep mountains and mountain ranges that don't become stone-tipped tend to look quite barren without them.

**Comment by yurisuika** [comment]
An idea for this would be setting elevation ranges (a min and max) for the tree features. So you could still have the same biome, but depending on the elevation, different trees would be placed. This would create a lot more variation in each biome. Perhaps this could be a setting for each feature in a random selector instead of multiple feature JSONs to do different ranges.

For example, I'd like to make it so my tree sets gradually produce smaller trees the higher the elevation goes up a mountain. Even if the individual chances remain the same in one config, the overlapping of those ranges would work to fade out the distribution. At least it seems to make sense in my head.
