### ISSUE TITLE
River-gen overhaul

### ISSUE THREAD

**Issue by dags-** [TerraForged/TerraForged#115]
Improve the river & lake generation system to enable finding more successful river paths while hopefully reducing the number of attempts to do so

**Comment by zeyd6796** [comment]
Is it possible to generate more vegetation along the river banks as a result of suitable moist locations? We can observe the line of plants bulging around the streams in [real life](https://www.researchgate.net/figure/a-The-natural-flow-of-river-showing-the-total-appearance-of-the-river-banks-Here-its_fig2_312181405).

**Comment by dags-** [comment]
There's a ticket open for river decorations here #80, feel fee to add your thoughts
This one's specifically for the actual generation of the river paths

**Comment by cmmdmx** [comment]
It also would be nice to add some more noise for the small rivers (more curves) 
When using Maps like journeymap they sometimes are just a very long straight line which appears unnatural. 
Also it would be VERY awesome to add some river-vegetation such as bushes, sand, gravel, small trees, small stone formations - even in Plains. This would look way more natural and interesting!

**Comment by Spirolateral** [comment]
All of this would be very cool! One thing that I'd personally like to see would be more elaborate networks of tributaries, so that big rivers are formed by small rivers coming together rather than simply being small rivers that get wider. It would also be amazing to have rivers that flowed downhill rather than simply staying horizontal, so that there could be small rivers and streams up in the mountains.
