### ISSUE TITLE
Biomes O' Plenty - Nether compatibility

### ISSUE THREAD

**Issue by ElChinooo** [TerraForged/TerraForged#133]
**I'd like to point out that there's no sign of any BOP nether biomes being generated.**

**Comment by STOKE-STER** [comment]
Was wondering why my nether looked so shit, this is it.

**Comment by demonJ5** [comment]
See "Add Option to Search for Nether Biomes" #86

**Comment by Voronoiii** [comment]
Bare in mind there are external mods that solve this on the latest version. If this issue is referring to the nether dimension and several biomes this isn't difficult at all. In all fairness i I agree w/ what Dags said in #86 this mod should stay true too the overworld. It might even be a bad idea if he hardcodes the nether on the world type. It could create complications for a user who wants say a 256 high nether. 

My mod solves this issue. Just add the biome's registry name in the config. And If i recall correctly, BOP's nether can't take in modded nether's from other mods bc of how the nether is setup. 

Link to the solution for this:
https://www.curseforge.com/minecraft/mc-mods/nethergenplus

**Comment by demonJ5** [comment]
Thanks for linking Nethergenplus, Voronoiii. That's exactly what I needed.
