### ISSUE TITLE
Biome config support for Serene Seasons

### ISSUE THREAD

**Issue by LordTerken** [TerraForged/TerraForged#140]
**Is your feature request related to a problem? Please describe.**
When using the Serene Seasons mod there is no easy way to change the seasonal preferences for the Terraforged biomes. Ex: During winter the weather will change to snow in the steppe & cold steppe biomes, but it will not form on the ground. 

**Describe the solution you'd like**
Mod support for the Serene Seasons mod. 

**Describe alternatives you've considered**
If possible, a personal method to resolve the issue

**Comment by dags-** [comment]
That mod modifies all biomes' code to use it's own weather/temperature system. TF doesn't do anything special/unusual with it's biomes so not sure what can be done on my end.

Note that SS is marked as beta so maybe not all features are 100% updated to 1.15.2 yet

**Comment by augustolobo18** [comment]
I had the exact same problem. I built my house in the steppe biome, and when winter arrived, it snowed but it wouldn't accumulate. Also riven water doesn't freeze. I searched in the code and I found out that SS actually work with biomes o plenty, because it has code in the biomes part for biomes o plenty biomes. So I tried to insert terraforged:steppe there but when I opened the game again the SS mod failed to load...
