### ISSUE TITLE
Lost Cities Incompatibility

### ISSUE THREAD

**Issue by FoundSpore** [TerraForged/TerraForged#17]
Nothing Happens with Lost Cities. 0 City Structures generate.

Lost Cities V1.15.2-3.0.0-alpha

**Comment by dags-** [comment]
Taking a scan of their repo, this line would be an issue:
https://github.com/McJtyMods/LostCities/blob/1.15/src/main/java/mcjty/lostcities/worldgen/LostCityFeature.java#L30

TF currently wraps the WorldGenRegion in order to override Vanilla's hard-coded sea level and a couple of Biome related methods. The wrapper currently just implements IWorld as this fits the method signature of the `Feature.place` method. I could possibly subclass WorldGenRegion instead.

This being said, I don't know if the TC feature is getting called at all in the first place - the curseforge page suggests the mod uses a specific world-type but perhaps that's for older versions.

**Comment by dags-** [comment]
Seems to have fixed it:
![2020-03-03](https://user-images.githubusercontent.com/4276064/75776315-acb9a780-5d4b-11ea-9073-7d56fb0560fa.png)

Not sure if it's supposed to flatten out tall terrain quite so much or if there's another compatibility issue where it's not receiving the correct height data for the terrain

**Comment by dags-** [comment]
This'll be fixed in the next release
