### ISSUE TITLE
The possibility of limiting certain biomes to specific terrain types and temperature band size customization

### ISSUE THREAD

**Issue by HermeticPrince** [TerraForged/TerraForged#177]
This is half suggestion and half a question (because i don't know if it really is possible) but i imagine it'd solve some of the problems (like the rarity of deserts since they're altitude-dependant).
For example: letting the user limit Mesas/Badlands or (modded) Highlands variants to the Plateau terrain type, since they don't really fit thematically and aesthetically with plains or steppes.
Also: i am not sure if i should open another post, but another suggestion that i believe would help would be making the biome size and the temperature bands independant sliders, since while some biomes (specially modded ones) look weird when they're too small, if you increase their size getting to another temperature "region" gets incredibly hard, specially on survival.
If, lets say, the biome size was set to "200" and the temperature band was set to "1000", you'd have to walk through 5 biomes of a specific temperature region to get to another, but if the biome size was changed to "500" and the temperature band remained at "1000" you'd only have to walk through 2 bigger biomes.
Forgive me if those suggestions are impossible or impractical, since i don't know much about mod development.

**Comment by Quizer9O8** [comment]
Having full control of biome customization is always a good thing. Being able to limit certain biomes to either terrain/region types (in combination of climate zones) would prevent mismatches with certain biomes.

**Comment by dags-** [comment]
The biomes/terrain thing causes issues elsewhere as a single biome cell can span across a terrain region border which would produce unnaturally straight edge biome transitions.

This would break biomes with specialised surfaces - for example I'd like to add dunes at some point and the height of those dunes would need to fade towards the edge of the biome. If that biome is cut off in the middle because the terrain has changed then you get a cross-section of dune right on the biome border.

----

Biome size and the climate controls will be (partially) decoupled in 0.1.x. There's already an issue open for it somewhere I think.
https://c1ip.me/TLVRDg
