### ISSUE TITLE
User-control over biome selection

### ISSUE THREAD

**Issue by dags-** [TerraForged/TerraForged#20]
Reimpliment the biome selection gui or at-least a ui for blacklisting them

**Comment by 2kai2kai2** [comment]
Would also be useful to be able to force all the biomes to be switched to vanilla biomes rather than any added by the mod so that the save can be switched to a vanilla (e.g. spigot) server after pregen without a need to either manually switch the biomes with third-party tools or just deal with regions where biome-specific events such as mob spawns don't happen.

**Comment by Artellia** [comment]
I am having biome issues with other mods that would be most easily solved by terraforged having a biome blacklist config of sorts, either during world gen or as a config file. It seems other mod writers don't always know the difference between not generating a biome and not registering it.

**Comment by dags-** [comment]
biome weights config added to 0.1.0
