### ISSUE TITLE
Is it possible for one to make a Spigot plugin of this?

### ISSUE THREAD

**Issue by Sam54123** [TerraForged/TerraForged#23]
Looking at the code, it looks like you've abstracted out the world-gen code from the forge mod code in the form of a separate Gradle project. Given that, aside from some UI stuff, all of the mod's functionality is server-side, is it theoretically possible for one to turn this project into a Spigot plugin for use on SMPs where the owner doesn't want to force the players to download a client-side mod?

**Comment by dags-** [comment]
Short answer: yep

The only reason there's a client-side requirement with the forgemod is because I add a couple of new biomes. These aren't essential and I'm sure some server-only equivalent would be achievable. Virtual/fake biomes? I don't know if there's a term for it.

Also discussed here: https://github.com/TerraForged/TerraForged/issues/21
