### ISSUE TITLE
Server Gen

### ISSUE THREAD

**Issue by TheShadowMC00** [TerraForged/TerraForged#283]
Hello, I am trying to make a realistic Minecraft server so I am using terraforged on it but whenever I set the level-type= to terraforged it turns it to default and creates it as default. I recreated my server many times now and it still does not work.

**Comment by Won-Ton** [comment]
A checklist of what you need:
1. a working forge server
2. the TerraForged mod jar placed in the server's `/mods/` folder
3. the `level-type` to be set to "terraforged" (no quote marks)
4. remove/rename any existing world folders so that the server generates a new one when it starts up

There's a more detailed guide for server setup here:
https://github.com/TerraForged/community/wiki/Forge-Server
