### ISSUE TITLE
Imcompatability with minecolonies 

### ISSUE THREAD

**Issue by Connorathomson121297** [TerraForged/TerraForged#285]
**Description**
While using the mod, minecolonies, after building 2 or 3 building, and exiting the world, the world takes 1-2 minutes to load, and up to 30 minutes to load with a full kingdom
**How to reproduce**
- I am using the multimc launcher.
- Minecolonies 13.383
- install minecolonies, and Terra forged, create terraforged world, create 1 or 2 buildings within mine colonies exit out ( it will take a bit) and then try to reenter world. will take up to 2 minutes  

**Additional information**
I have tried with other world types and they comply just fine

**Comment by dags-** [comment]
Need debug logs from the session where the problem occurred

**Comment by dags-** [comment]
You need to just drag-drop the log file into the comment box in this thread to upload it

**Comment by Connorathomson121297** [comment]
[2020-10-25-1.log](https://github.com/TerraForged/TerraForged/files/5434220/2020-10-25-1.log)

**Comment by dags-** [comment]
The logs don't show enough detail as it seems multimc strips a lot of the fine detail. Please try recreate the issue on the official launcher with just mineconolies and TF installed and provide the 'debug.log' from that.

**Comment by Connorathomson121297** [comment]
oh sorry that was just the log. i'll post the debug log here now
[Uploading debug-1.log…]()

**Comment by dags-** [comment]
(you submitted your comment before the upload completed)

**Comment by Connorathomson121297** [comment]
[debug-1.log](https://github.com/TerraForged/TerraForged/files/5434244/debug-1.log)

**Comment by dags-** [comment]
Unable to reproduce with just TF and minecolonies.

I do get a ~10s pause at the end of the loading screen where it says 'Joining world'. This happens after TF's chunk generator has been created and any missing chunks generated so I'd assume it's minecolonies loading/sychronizing its data from the world - I don't know what is normal in that regards. I have a decent number of CPU cores so maybe the slowdown scales negatively with lower core-counts.

I also profiled the setup and found that TF/chunk-generation wasn't active during that pause or otherwise doing anything unexpected.
