### ISSUE TITLE
Biome Serialization 

### ISSUE THREAD

**Issue by NillerMedDild** [TerraForged/TerraForged#29]
**Description**
Latest.log is completely filled with NPEs about biome features that can't be serialized.
Sometimes the world loads fine, sometimes it doesn't - It never crashes though.
It seems that depending on the seed, biome features from vanilla will also fail to be serialized, also causing tons of NPEs.

**How to reproduce (get your mind out of the gutter! -_-)**
- Using Twitch, with the modpack Enigmatica 5 development branch
- Related mods: ultra_amplified_dimension-1.15.2-7.2.3

1) Make an instance with TerraForged and Ultra Amplified Terrain. (I think some seeds will have issues without UAT)
2) Launch, and create a new TerraForged world.
3) Look at the latest.log

**Additional information**
https://gist.github.com/NillerMedDild/0874052ed233231120ee0e1f8c99b749

**Comment by dags-** [comment]
These exceptions are caused by third-party mod Features that are not fully/correctly implemented.

TerraForged catches and handles these errors so they are not causing any problems for the normal operation of the game, it just means that certain advanced configuration options in TF cannot be used with these Features.

I know it looks a bit spammy in the console but it's potentially useful information to record for identifying compatibility issues in the future. I could probably change the log level of these messages to debug at least

**Comment by NillerMedDild** [comment]
A lower log level would be nice :) 
I'll let the Ultra Amplified dev know about this issue, thanks!
