### ISSUE TITLE
I tried it...

### ISSUE THREAD

**Issue by Barerock** [TerraForged/TerraForged#295]
Same versions and everything, I made a comment earlier.

Tried newest version and the BoP issues are still present. Volcanoes and Umbral woods are the ones I care about most, but there are a couple other biomes totally absent from the world after travelling hundreds of thousands of blocks in random directions and searching in a 10k radius each time. 

Most other things seem to be fixed, and I was going to suggest an option to make a large type biome setting for servers (Imagine a desert being actually dangerous because of no shelter, food, or wood for days of travel, Gobi and Sahara type huge) but I haven't checked the in game settings. I'll rehash once I figure that stuff out, because that idea sounds awesome to me.

Thanks

**Comment by Won-Ton** [comment]
TF doesn't guarantee that 100% of other mods' biomes will be used because it's not possible to 100% accurately identify and categorise all of them. You can use `/terra locate biome` & `/terra locate terrain` to see if any exist in the world from your location.

If you want a better chance of finding most biomes then reduce the climate/biome sizes. If you want giant deserts increase the biome/climate sizes
