### ISSUE TITLE
Server support?

### ISSUE THREAD

**Issue by Miloszun** [TerraForged/TerraForged#36]
How do you set up this mod so that you can play on a server? I think it has something to do with the level type variable, but I don't know the right phrase to write.

**Comment by dags-** [comment]
Normally you'd set `level-type=terraforged` in the server.properties file, but forge doesn't support this yet.

The workaround is to create the world in single-player and simply copy it over to your server

**Comment by IPlayZed** [comment]
I have the following problem: when new chunks are generated, they are vanilla chunks.
I provided a detailed description with console output:
[consoleop.txt](https://github.com/TerraForged/TerraForged/files/4329699/consoleop.txt), a screenshot of it,
![2020-03-13_13 32 28](https://user-images.githubusercontent.com/21132316/76623627-21eb6080-6534-11ea-9093-c50d3cf1b288.png)my single-player world and server-snapshot, captured as it is written in readme file (due to sizes I uploaded it to Google Drive):https://drive.google.com/file/d/1Slr3VZDXmjDdM5OSBhpsq3amX35KzfN1/view?usp=sharing
https://drive.google.com/file/d/17941ut01HmVaKJMN0lZxNtMew4YAlEn2/view?usp=sharing
Please tackle this issue, as it makes this amazing mod currently unusable in multiplayer.

**Comment by dags-** [comment]
@IPlayZed Hi, the logs look to be from a vanilla server. 

The startup command:
`java -Xmx5G -Xms1024M -jar minecraft_server.1.15.2.jar nogui`

`minecraft_server.1.15.2.jar`  looks like the vanilla server jar. You probably want to be launching with `forge-xxx-xxx.jar`?

**Comment by IPlayZed** [comment]
@dags- It start, but it crashes, here is the report:
[crash-2020-03-13_12.21.41-server.txt](https://github.com/TerraForged/TerraForged/files/4329825/crash-2020-03-13_12.21.41-server.txt)

**Comment by dags-** [comment]
You'd need to seek support from Forge for that. I could take a guess that it's because you're using java 13 (I think java 8 is recommended at the moment) but I'm not sure.

Once you've got your forge server running with no mods installed, it should just be a case of adding TerraForged to your server's `./mods` folder. If you're having trouble after that, feel free to open a new ticked here

**Comment by IPlayZed** [comment]
I will try to run the server without TerraForged.

**Comment by IPlayZed** [comment]
Thank, you using Java 8 runtime environment solved it!
Please be sure to include this is in instruction for setting up the server, it could save time for newcomers.
