### ISSUE TITLE
Does this change any ore generation?

### ISSUE THREAD

**Issue by piisawheel** [TerraForged/TerraForged#40]
Can I expect my resources at vanilla layers? Or does this muck with any of that?

**Comment by dags-** [comment]
I don't alter the quantities or the placement style of ores, but I've generally increased the heights at which it's possible for ores to spawn (this is to account for the taller terrain that TF generates compared to vanilla).

Note that is for vanilla ores only. I don't touch mod ores.

You can find the configs for ores here:
https://github.com/TerraForged/TerraForged/tree/master/TerraForgedMod/src/main/resources/data/terraforged/features/ores

These same files exist inside the mod jar which you can edit to your liking if you want.

**Comment by guillermofbriceno** [comment]
Testing ore counts with WorldEdit, the total number of ores are the same compared to vanilla generation as dags says. But since their height probabilities have been stretched out, each vertical cross section will have less ore than vanilla generation. In my testing, your tunnels would have to be twice as tall to come close to vanilla density. This makes branch mining less effective and caving more grind-y. I'll leave whether or not this is intended behaviour up to the author, just wanted to shed more light on the issue.

**Comment by Artellia** [comment]
I'd love for you to take a fresh look into the question of ore gen. I am finding the max height I encounter coal, much less anything else to be y105. This leaves 70 or more blocks above that in mountains completely devoid of ore. As was pointed out above, the stretching out of the ore gen, even to the height limits currently set, leaves the overall density much lower. I suggest some slider settings that allow the user more control over ore generation heights and densities.
