### ISSUE TITLE
Prevent the player from spawning in the ocean. Reduces need to swim to land early-game.

### ISSUE THREAD

**Issue by CreativeRealms** [TerraForged/TerraForged#57]

**Comment by arutr** [comment]
You can see in the preview whether the spawn is ocean or not?

**Comment by CreativeRealms** [comment]
I think the preview is more for showing what the world could look like rather than the actual spawn point you'll end up in.

**Comment by dags-** [comment]
This is related to the stronghold thing actually (I think) - they both use the same lookup method to find a biome position but my implimentation of it was searching at 1/4 the range that it should have been. Because it was searching a much smaller area it would often fail to find the desired biome, at which point the default would become 0,0 (plus a random offset).

I can't guarantee that spawn will always find land because 0, 0 may be the center of a gigantic ocean, and even with the fixed lookup method it may be too large for the search. Hopefully it'll be much improved though
