### ISSUE TITLE
Problem with walking/running.

### ISSUE THREAD

**Issue by WolfDraal2559** [TerraForged/TerraForged#77]
_Please take a look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported and reply to that rather than creating a new thread :)_

**Description**
When i am walking or running, also in the air. I am getting stopped almost every "two steps" (almost because there are few times when everything is working correctly). when i push space to "autojump" i jump, then walk one/two steps and then jump. 

 

**How to reproduce**
- Describe your setup if using anything other than the Mojang launcher or standard forge server
- List any third-party mods (& their version number) that may be relevant to the issue
- Provide a simple step-by-step guide to recreate the problem

**Additional information**
i have also falling tree mod

**Comment by dags-** [comment]
First thing to check would probably be your ram - you may simply need to allocate a bit more to minecraft in whatever launcher you're using.

If not that, then it might be your cpu & graphics card struggling to render everything. TF generally produces taller worlds so there's more stuff to compute & render. Reducing render distance can help enormously.

**Comment by WolfDraal2559** [comment]
Weird i got 10 GB of REM allocated for minecraft and it uses max 6-7GB. CPU and GPU usage during the game is also normal,20-40%

**Comment by WolfDraal2559** [comment]
My render distance is 7 or 8. I use original minecraft launcher.

**Comment by dags-** [comment]
Terraforged is only doing work when you generate chunks. If you're having performance issues outside of that then it's probably not TF that's the issue.

If you're familiar with the debug screen, it might be worth running around with that open with the frame-time & tps graphs up as they hint towards what your problem is.

Personally, I have encountered stutters with Vanilla 1.15.2 when crossing chunk boundaries. Don't know why, seems to be exacerbated when using high render distances. I haven't found a fix :/

**Comment by WolfDraal2559** [comment]
Ok. Thanks for help ill see debug screen
